### ISSUE TITLE
l function does not work (anymore)

### ISSUE THREAD

**Issue by narduin** [Alexandre-Fernandez/astro-i18n#11]
I don't know if it's `astro@1.7.0` or something else but I think the route translation using the `l` function is broken.

I tried using translated routes in `astro.i18n.config` and in folders with `{route}` but neither seem to work anymore.

I reverted back to `astro-i18n@1.3.2` and it seemed to work as expected with `astro@1.7.2`.

[The demo repo](https://github.com/narduin/astro-i18n-test/tree/bug/translated-route) is up to date with an example.

**Comment by Alexandre-Fernandez** [comment]
I'll check this after, I probably broke it yesterday. I'll try to fix this today.

**Comment by Alexandre-Fernandez** [comment]
everything should be fixed in [1.4.5](https://github.com/Alexandre-Fernandez/astro-i18n/pull/12)
