### ISSUE TITLE
Extract Function Enhancements

### ISSUE THREAD

**Issue by lorenzolewis** [Alexandre-Fernandez/astro-i18n#17]
With the extract function added in https://github.com/Alexandre-Fernandez/astro-i18n/pull/15 (thank you!!!) it's a really good start!

It supports the use case where you are only storing _keys_. Another use case is where you're storing the actual string of your source language (i.e. English) in your JS/TS files directly.

So instead of a function like this:

```astro
<html>
  <body>
    <p>{t("index.content")}</p>
  </body>
</html>
```

You would instead do this:

```astro
<html>
  <body>
    <p>{t("I'm the title of a page. I have white spaces, punctuation, and all kinds of things that could make escaping difficult!")}</p>
  </body>
</html>
```

Right now this isn't very robust. For example, if the string of text ends up wrapping like this:

```astro
<html>
  <body>
    <p>{
      t(
          "I'm the title of a page. I have white spaces, punctuation, and all kinds of things that could make escaping difficult!"
      )
    }</p>
  </body>
</html>
```
It won't extract.

All this to be said, I appreciate the many different edge cases this could potentially open up. Would you be open to a system that's parsing the AST of an astro file instead of a more brute-force regex method? If so then I could look into opening a PR for it potentially.

**Comment by Alexandre-Fernandez** [comment]
Indeed that would be a much less hacky way to do it. 
If you want to help out, I'll gladly merge your PR !

**Comment by Alexandre-Fernandez** [comment]
@lorenzolewis I fixed the extraction feature for most use cases. 
It should always work except if you have `")` or `')` in your string.
Tell me if you want to improve this further, else I'll close the issue.
