### ISSUE TITLE
`sync` doesn't seem to happen automatically during dev cycle?

### ISSUE THREAD

**Issue by reefdog** [Alexandre-Fernandez/astro-i18n#20]
@Alexandre-Fernandez This is a fantastic library and I've really enjoyed using it. Thank you!

When developing my Astro 2 project, I regularly add pages and translation strings with the dev server running (`npm run dev`). I would _expect_ that these new translations would show up automatically; however, I seem to have to stop the dev server, run `i18n:sync`, and then restart it for them to show up in the template, or for the new routes to be built.

I can go into more detail if this sounds unexpected, but first I'm just curious: are you supposed to be able to add new templates, routes, translations, etc. while the dev server is running, and they Just Work? Or is it known that you have to stop, resync, and restart?

**Comment by reefdog** [comment]
Quick note to add: this only applies to the i18n-relevant bits (routes with language codes, etc.). Other Astro-built templates and routes build fine. It's just the i18n brain that needs to sync each time.

**Comment by Alexandre-Fernandez** [comment]
At the moment all state is loaded at build time. This would be a great feature to add.
However I don't have much time to dev this library these days, I'll check the documentation on how to implement this and if it's not too time consuming I'll try adding it. That or make a PR :)

**Comment by reefdog** [comment]
@Alexandre-Fernandez I'd be happy to contribute if I'm able, though it may be beyond my abilities. Mostly I wanted to figure out what the intended behavior was, to figure out if I should continue working around it or resolve the problem.

**Comment by lorenzolewis** [comment]
I had a quick look through the hooks available in Astro and I don't think any would really achieve this. You'd probably want something that integrates into your IDE that can trigger a command upon saving a file.

For VS Code a popular extension seems to be [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave). I haven't tested this myself so I'm not sure how well Astro/TypeScript will play with this being run and then being able to successfully pick up the updated type definitions. I've had a few issues with the Astro Language Server in VS Code stopping randomly but it could be an issue with my setup.

**Comment by Alexandre-Fernandez** [comment]
Translations should be added on every page refresh with the new version.
As for automatically generating pages and types I will probably add it under a flag in the config.
