### ISSUE TITLE
Using astro-i18n with new content folder

### ISSUE THREAD

**Issue by agonist** [Alexandre-Fernandez/astro-i18n#25]
Hi, first great job, I'm enjoying using the library and would be potentially keen to contribute.

I have successfully published a website using it, but now that I want to add a blog section, I wonder how to combine this lib with the new Astro content folder.

if simply using it naively with a `[slug].astro` page and my md files in the content folder we will endup having duplicated route in each language.

What I'm expecting to have: 
- `/blog/article-1-in-english`. // default language
- `/fr/blog/article-1-in-french` // second language

But what is being generated let you access: 
- `/blog/article-1-in-english`.
- `/blog/article-1-in-french`.
- `/fr/blog/article-1-in-english` 
- `/fr/blog/article-1-in-french` 

Which is normal considering how both systems works. So I'm wondering, at which level could we make sure this does not happen ? I'm not an Astro expert yet but if something could make it happen I'd be happy to try and implement it.

Maybe by giving the possibility to ignore some page in the i18n.config it could helps 🤔

**Comment by oliviergraziano** [comment]
Hey,
I ran into the same issue, so I created a repo to demonstrate it
https://github.com/oliviergraziano/astro-i18n-content-incompatibility

Happy to help debugging this if needed :)

**Comment by narduin** [comment]
Hey @agonist, I made my website using Astro content folder and this very plugin for translating everything (french and english).
You can check out how I did it [here.](https://git.nardu.in/nardu.in/website-astro)
The logic behind single post translation is [here.](https://git.nardu.in/nardu.in/website-astro/src/commit/b1fbffc23fc6892d37ccbcfa495bc9684a115d6f/src/pages/articles/%5Bslug%5D.astro#L10-L18)

I'm not saying this is the proper way but it works so far :)

**Comment by agonist** [comment]
@narduin sounds great ! I will take a look thanks.
didn't had time to work on it again but if I'm still running into the issue I'll post a repo.
