### ISSUE TITLE
Wrong paths generated on sync

### ISSUE THREAD

**Issue by alexpi** [Alexandre-Fernandez/astro-i18n#26]
Hello,

When syncing, the generated page files have imports containing backward slashes, and this produces an error:
```js
---
import Page from "..\index.astro"
const { props } = Astro
---
<Page {...props} />
```
I am using Astro on Windows 10.

**Comment by Alexandre-Fernandez** [comment]
I don't have any windows machine to test and fix this.
The import path generation happens [here](https://github.com/Alexandre-Fernandez/astro-i18n/blob/2eaca61b939bd22cc6ddb33459f38e760a2d0b26/src/core/fs/generators/page.proxy.ts).
I'll be happy to merge a PR if it does not break anything.

**Comment by abdelrazzaq-dev** [comment]
same problem on ubuntu!

**Comment by Alexandre-Fernandez** [comment]
> same problem on Ubuntu when I set `showDefaultLangCode` to false.

I'm on Ubuntu and I don't have that problem, please provide a reproduction repository.

**Comment by abdelrazzaq-dev** [comment]
> > same problem on Ubuntu when I set `showDefaultLangCode` to false.
> 
> I'm on Ubuntu and I don't have that problem, please provide a reproduction repository.

The issue was fixed after I updated Astro!
