### ISSUE TITLE
`sync:pages` doesn't remove old pages

### ISSUE THREAD

**Issue by lorenzolewis** [Alexandre-Fernandez/astro-i18n#35]
If you create a page in your standard route, run `sync:pages`, and then remove that page in your standard route it will still be there. This can cause an issue where the old page for the non-standard route still gets built (or throws an error if it isn't able to be built).

It'd be a nice DX/quality of life improvement to either:

a) Have the `sync:pages` command automatically purge any files in the target directories to be written to or...
b) Introduce another CLI command (maybe `sync:purge` or similar) that a dev could explicitly run prior to `sync:pages`.

I'd personally go for option a) above (maybe with a parameter in the config to enable/disable) as this would seem to be the better DX.

If you agree with this I can take a stab at putting in a PR for this one (just let me know which option you prefer).

**Comment by OfekA-IAI** [comment]
If anyone needs this functionality, we wrote a short script:

_delete-existing-translation-pages.ts_
```typescript
import fs from "fs";
import path from "path";
import { languages } from "../astro.i18n.config";

languages
  .filter((lang) => lang.ietf !== "en")
  .forEach((lang) => {
    console.log(path.resolve(`src/pages/${lang.ietf}`));
    const dirToDelete = path.resolve(`src/pages/${lang.ietf}`);
    try {
      fs.accessSync(dirToDelete);
      fs.rmdirSync(dirToDelete, { recursive: true });
    } catch (e) {
      // console.error(e);
    }
  });
```

_package.json_
```json
"scripts": {
    "i18n:sync": "tsx ./scripts/delete-existing-translation-pages.ts && astro-i18n sync",
  },
```

**Comment by Alexandre-Fernandez** [comment]
I just added this to v2.0, I will close the issue when it's released.
