### ISSUE TITLE
Variables in snake cases are ignored during translation

### ISSUE THREAD

**Issue by ankuradhey** [Alexandre-Fernandez/astro-i18n#39]
**Describe the bug**
`t()` is ignoring any variables passed in snake case and accepting camel cases. I am calling t function like this

_index.astro_
```
t('home.title', {'user_name': 'Test user', userName: 'Demo user'});
```

_astro.i18n.config.ts_
```
export default defineAstroI18nConfig({
    defaultLangCode: 'en-gb',
    supportedLangCodes: ['fr-fr'],
    showDefaultLangCode: true,
    translations: {
        'en-gb':{
            "home.title": "Welcome to {user_name} {userName}!"
        }
    }
})
```

***Current result***
Welcome to Demo user!

***Expected result***
Welcome to Test user Demo user!

Am I missing something or is this a bug?

**Comment by Alexandre-Fernandez** [comment]
If it works with camel case it's probably a bug.
I'll see what I can do. Thanks for your report.

**Comment by ankuradhey** [comment]
@Alexandre-Fernandez Any luck?

**Comment by Alexandre-Fernandez** [comment]
I'm currently developing 2.0 which will fix this bug and improve many other things

**Comment by ankuradhey** [comment]
> I'm currently developing 2.0 which will fix this bug and improve many other things

Amazing! Thanks for the update. I look forward to that release.

**Comment by Nkay** [comment]
Can we sponsor this? We don't use it on a big page but I see the work and the potential ;)

**Comment by Alexandre-Fernandez** [comment]
> Can we sponsor this? We don't use it on a big page but I see the work and the potential ;)

Thanks, I'll try to setup something then !
