### ISSUE TITLE
Translated routes and translation does not work with 404 pages

### ISSUE THREAD

**Issue by mutheusalmeida** [Alexandre-Fernandez/astro-i18n#40]
**Describe the bug**
I've noted that translated routes and and translation does not work with 404 pages because Astro.url.pathname returns 404 and not the actual pathname.

**To Reproduce**
1. Go to a translates and non existing url
2. Click on the language switcher component and select a language
4. The url exibits /404 and translation does not work

**Expected behavior**
The url should switch from /articles to /pt-BR/artigos

**Comment by Alexandre-Fernandez** [comment]
Please provide a reproduction repository.
