### ISSUE TITLE
"readFileSync" is not exported by "__vite-browser-external", imported by "node_modules/astro-i18n/dist/src/index.mjs".

### ISSUE THREAD

**Issue by raremiroir** [Alexandre-Fernandez/astro-i18n#51]
**Describe the bug**
Getting weird vite error on build; "readFileSync" is not exported by "__vite-browser-external", imported by "node_modules/astro-i18n/dist/src/index.mjs".

Any help here? Is this error related to i18n or rather to Vite?
Honestly have no idea what's causing this.

<details>
<summary>Console error log</summary>
<br>
"readFileSync" is not exported by "__vite-browser-external", imported by "node_modules/astro-i18n/dist/src/index.mjs".
file: C:/Users/user/mistmedia-be/node_modules/astro-i18n/dist/src/index.mjs:1:1713
1: var J=(t,n,r)=>{if(!n.has(t))throw TypeError("Cannot "+r)};var h=(t,n,r)=>(J(t,n,"read from private field"),r?r.call(t):n.get(t)),C=(t,n,r)=>{if(n.has(t))throw TypeError("Cannot add the same private member more than once");n instanceof WeakSet?n.add(t):n.set(t,r)},$=(t,n,r,e)=>(J(t,n,"write to private field"),e?e.call(t,r):n.set(t,r),r);var at=(t,n,r)=>(J(t,n,"access private method"),r);import{fileURLToPath as Un}from"url";function m(t){return Object.getPrototypeOf(t)===Object.prototype}function k(t){return Array.isArray(t)&&t.every(n=>typeof n=="string")}function ft(t){if(!m(t))return!1;for(let n of Object.values(t))if(typeof n!="string")return!1;return!0}function ut(t){if(!m(t))throw new Error(`"${t}" is not of type Record<string, string>.`);for(let n of Object.values(t))if(typeof n!="string")throw new TypeError(`"${n}" is not of type string.`)}function Y(t,n){if(!t.includes(n))throw new Error(`${n} is not in [${t.join(", ")}].`)}function A(t){return Object.entries(t)}function lt(t,n,r){let e=t;for(let[o,i]of n.entries()){if(o===n.length-1){e[i]=r;break}if(!ct(e,i)){e[i]={},e=e[i];continue}if(Object.getPrototypeOf(e[i])===Object.prototype){e=e[i];continue}break}}function y(t,n,r){let{mode:e,modifyBase:o}={mode:"replace",modifyBase:!0,...r},i=o?t:H(t);for(let[a,s]of A(n)){let f=i[a];if(ct(i,a)){m(f)&&m(s)?y(f,s):e==="replace"&&(i[a]=n[a]);continue}i[a]=n[a]}return i}function H(t){return!t||typeof t!="object"?t:Array.isArray(t)?t.map(n=>typeof n=="object"?H(n):n):A(t).reduce((n,[r,e])=>{let o=n;return o[r]=H(e),n},{})}function ct(t,n){return Object.prototype.hasOwnProperty.call(t,n)}import Zt from"get-file-exports";import{readdirSync as Bt}from"fs";import{join as qt}from"path";import{readFileSy...
<br><br>
2: Add "${o}" to ${c}.supportedLangCodes or ${c}.defaultLangCode).`);if(typeof i!="string"){if(!m(i))throw new TypeError(`${c}.translations.${o} must be either a translation object or a (string) path to a json one.`);for(let[,a]of Object.entries(i))Rt(a)}}}function Ht(t,n){if(!m(t))throw new TypeError(`${c}.routeTranslations must be an object literal.`);let r=[];k(n)&&r.push(...n);for(let[e,o]of Object.entries(t)){if(r.length>0&&!r.includes(e))throw new TypeError(`${c}.routeTranslations.${e}, unsupported lang code.
3: Add "${e}" to ${c}.supportedLangCodes).`);if(typeof o!="string"&&!ft(o))throw new TypeError(`${c}.routeTranslations.${e} must be either a Record<string, string> or a (string) path to a json one.`)}}function D(t){if(typeof t=="string")return!0;if(!m(t))return!1;for(let n of Object.values(t))if(!D(n))return!1;return!0}function Rt(t){if(typeof t!="string"){if(!m(t))throw new TypeError(`"${t}" must be either a string or a translation object.`);for(let n of Object.values(t))Rt(n)}}var Et=new Set(["json","js","cjs","mjs","ts","cts","mts"]),Xt={defaultLangCode:"en",supportedLangCodes:[],showDefaultLangCode:!1,trailingSlash:"never",translations:{},routeTranslations:{}};function Q(){return{...Xt}}function Qt(t){return t}async function Ot(t,n=""){let r=tn(t,n),e=r.endsWith(".json")?I(r):(await Zt(r)).default;return At(e),nn(e,t)}function tn(t,n=""){if(n){if(!q(n))throw new Error(`${n} is not an astro-i18n config file.`);let r=dt(n);if(!Et.has(r))throw new Error(`The astro-i18n config file must be a JavaScript or TypeScript file (found "${r}").`);return n}if(!N(t))throw new Error(`${t} is not the project's root directory.`);for(let r of Bt(t)){let[e,o]=Tt(r);if(!!Et.has(o)&&e===c)return qt(t,r)}throw new Error(`Could not resolve the astro-i18n config file, verify that you have a ${c}<.js/.ts> file in your project root directory "${t}".`)}function nn({defaultLangCode:t,supportedLangCodes:n,showDefaultLangCode:r,trailingSlash:e,translations:o,routeTranslations:i}={},a=""){let s=Q();if(t&&(s.defaultLangCode=t),n&&(s.supportedLangCodes=n),r!==void 0&&(s.showDefaultLangCode=r),e&&(s.trailingSlash=e),a){let f=[s.defaultLangCode,...s.supportedLangCodes];o&&(s.translations=rn(o,f,a)),i&&(s.routeTranslations=en(i,...
 error   "readFileSync" is not exported by "__vite-browser-external", imported by "node_modules/astro-i18n/dist/src/index.mjs".
  File:
    C:/Users/user/mistmedia-be/node_modules/astro-i18n/dist/src/index.mjs:1:1713
  Code:
    1: var J=(t,n,r)=>{if(!n.has(t))throw TypeError("Cannot "+r)};var h=(t,n,r)=>(J(t,n,"read from private field"),r?r.call(t):n.get(t)),C=(t,n,r)=>{if(n.has(t))throw TypeError("Cannot add the same private member more than once");n instanceof WeakSet?n.add(t):n.set(t,r)},$=(t,n,r,e)=>(J(t,n,"write to private field"),e?e.call(t,r):n.set(t,r),r);var at=(t,n,r)=>(J(t,n,"access private method"),r);import{fileURLToPath as Un}from"url";function m(t){return Object.getPrototypeOf(t)===Object.prototype}function k(t){return Array.isArray(t)&&t.every(n=>typeof n=="string")}function ft(t){if(!m(t))return!1;for(let n of Object.values(t))if(typeof n!="string")return!1;return!0}function ut(t){if(!m(t))throw new Error(`"${t}" is not of type Record<string, string>.`);for(let n of Object.values(t))if(typeof n!="string")throw new TypeError(`"${n}" is not of type string.`)}function Y(t,n){if(!t.includes(n))throw new Error(`${n} is not in [${t.join(", ")}].`)}function A(t){return Object.entries(t)}function lt(t,n,r){let e=t;for(let[o,i]of n.entries()){if(o===n.length-1){e[i]=r;break}if(!ct(e,i)){e[i]={},e=e[i];continue}if(Object.getPrototypeOf(e[i])===Object.prototype){e=e[i];continue}break}}function y(t,n,r){let{mode:e,modifyBase:o}={mode:"replace",modifyBase:!0,...r},i=o?t:H(t);for(let[a,s]of A(n)){let f=i[a];if(ct(i,a)){m(f)&&m(s)?y(f,s):e==="replace"&&(i[a]=n[a]);continue}i[a]=n[a]}return i}function H(t){return!t||typeof t!="object"?t:Array.isArray(t)?t.map(n=>typeof n=="object"?H(n):n):A(t).reduce((n,[r,e])=>{let o=n;return o[r]=H(e),n},{})}function ct(t,n){return Object.prototype.hasOwnProperty.call(t,n)}import Zt from"get-file-exports";import{readdirSync as Bt}from"fs";import{join as qt}from"path";import{readFileSy..
</details>

**To Reproduce**
1. Use my config
2. Astro build
3. Error

**Expected behavior**
Build process should work.

**Mandatory reproduction repository**
https://github.com/raremiroir/mistmedia-be

**Comment by mehmetakify** [comment]
Same issue for me. Is there any update?

**Comment by Alexandre-Fernandez** [comment]
this might happen because you are using the library in the client-side, if that's the issue it will be fixed in the next version

**Comment by Alexandre-Fernandez** [comment]
I'm closing this, try to retest with the new version, should be fixed, if not I'll open again.
