### ISSUE TITLE
Could not find a declaration file for module 'astro-i18n'.

### ISSUE THREAD

**Issue by LynithDev** [Alexandre-Fernandez/astro-i18n#52]
**Describe the bug**
When trying to import the library in any file, whether its a `.astro` or `.ts` file, TypeScript throws an error:
```ts
Could not find a declaration file for module 'astro-i18n'.
```

**To Reproduce**
1. Create / edit a file with TypeScript support
2. Try doing `import { astroI18n } from "astro-i18n";`

**Expected behavior**
No errors to be thrown and have types

**Mandatory reproduction repository**
~~None~~

**To fix**
When exporting / publishing the library, the type definition file should end with `.d.mts`, not `.d.ts` as the exported JavaScript file ends in `.mjs`

**Comment by Alexandre-Fernandez** [comment]
A TS update broke something. Anyway this should soon be fixed in the next major version. It's ready for release I'm writing the documentation right now.
