### ISSUE TITLE
Module '"astro-i18n"' has no exported member 'defineAstroI18nConfig'.

### ISSUE THREAD

**Issue by kalkson** [Alexandre-Fernandez/astro-i18n#53]
**Describe the bug**
Helper function is not correctly visible by resolver.

**To Reproduce**
1. Create new astro project
2. install `astr-i18n`
3. run auto config
4. go to `astro.i18n.config.ts`

**Expected behavior**
Util should be correctly visible by TypeScript

**Comment by Alexandre-Fernandez** [comment]
A TS update broke something. Anyway this should soon be fixed in the next major version. It's ready for release I'm writing the documentation right now.
