### ISSUE TITLE
Common translations aren't loaded from src/i18n

### ISSUE THREAD

**Issue by gislerro** [Alexandre-Fernandez/astro-i18n#55]
**Describe the bug**
Translations from the folder `src/i18n/common/` aren't loaded with the config generated by `./node_modules/.bin/astro-i18n install`. I've only added a secondary locale to my config in my reproduction.

**To Reproduce**
1. create a new astro project
2. install latest version of `astro-i18n`
3. perform setup as described in the `README.md`
4. create the translation files in `src/i18n/common/`

**Expected behavior**
`t('common.my_common')` should return the translation with ***no*** configuration in `astro-i18n.config.ts` as implied by the `README.md`

**Mandatory reproduction repository**
[See here](https://github.com/gislerro/astro-i18n-v2.0.0-repro)

**Comment by Alexandre-Fernandez** [comment]
I just fixed this thanks for reporting, I don't know how this passed the tests

**Comment by gislerro** [comment]
The issue is not yet fixed - it just displays the primary translation and doesn't respect the current locale. See the image below:

![image](https://github.com/Alexandre-Fernandez/astro-i18n/assets/63500142/0fd5770c-7df5-4034-9c1d-d868725604ee)

I've updated the reproduction repo.

**Comment by Alexandre-Fernandez** [comment]
Sorry for these errors, I already fixed it, I'm adding something else and gonna upload just after that.
Hopefully we can sort all these one line bugs quickly.

**Comment by amosbastian** [comment]
I am having the same problem and seems it still occurs in @gislerro's repository
