### ISSUE TITLE
Minimal example is not working

### ISSUE THREAD

**Issue by fprl** [Alexandre-Fernandez/astro-i18n#56]
**Describe the bug**
Hey there, thanks for checking this. These are the steps I took:

1. Created a new astro project and added the library with the serverless command:
```bash
./node_modules/.bin/astro-i18n install --serverless
```

2. Created `src/i18n/common/en.json` file.

3. Run `pnpm dev`.

Once I visit the index page, I get this error:
```
node:fs:1527
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir
```

Thanks!

**To Reproduce**
1. Run `pnpm dev`.
2. Visit index page.

**Expected behavior**
It should work, at least it should not give any error.

**Mandatory reproduction repository**
[Git repository](https://github.com/fprl/repro-astro-i18n)

**Comment by Alexandre-Fernandez** [comment]
@fprl What environment are you running it on ?

**Comment by fprl** [comment]
@Alexandre-Fernandez this is running in local (so dev) and with output server

**Comment by Alexandre-Fernandez** [comment]
@fprl try with `2.0.11`

**Comment by Alexandre-Fernandez** [comment]
By the way thanks for providing a repo, really speeds up debugging !

**Comment by fprl** [comment]
Thanks to you @Alexandre-Fernandez, love the new API.

I pushed new changes (just added `nl` as a secondary language and once I run `pnpm i18n:sync` I get the same error:

```
node:fs:1527
  handleErrorFromBinding(ctx);
  ^

Error: EPERM: operation not permitted, scandir '/Users/me/Library/Calendars'
```

Do you want me to create a new ticket?

**Comment by Alexandre-Fernandez** [comment]
No need, it's late, I'll fix that bug tomorrow.

**Comment by fprl** [comment]
@Alexandre-Fernandez thanks a lot Alexandre, now its working. The only thing I'm seeing right now is:
- `pnpm i18n:sync` generates the types for `i18n/common/*` but it seems the middleware is not taking into account this translations as they return the key string. If I put the translations in the middleware config then it works.
- Some methods in the astroI18n class may not be loading the config?
```typescript
console.log(astroI18n.page); // returns null
console.log(astroI18n.pages); // returns []
```

PS: I pushed changes.

**Comment by Alexandre-Fernandez** [comment]
Only the 3rd point is a bug.
> 1. pnpm i18n:sync generates the types for i18n/common/* but it seems the middleware is not taking into account this translations as they return the key string. If I put the translations in the middleware config then it works. Is this because its taking into account how edge serverless work (no node apis)?

You're not supposed to use anything related to the filesystem when doing serverless that's why it ignores it. 

> 2. BtwI was trying to access page and pages to create a localizedUrl utility. Some methods in the astroI18n class may not be loading the config?

This is my bad I didn't document it well, the library only takes pages that are in the translations into account.
For example when using serverless you will need to tell what are your pages in the config :
```ts
{
		translations: {
			"/": {},
			"/about: {},
			"/posts/[slug]: {},
		},
	}
```
Maybe I could think of a better way of doing it in the future.

As for the third point I'll open another ticket.

**Comment by fprl** [comment]
@Alexandre-Fernandez okay, all clear.
1. 
> You're not supposed to use anything related to the filesystem when doing serverless that's why it ignores it.

True, specially if you use edge functions. I guess if you would want to add something similar for this case (`--serverless` flag), it could run the same script as you do on runtime and create a unified translation object to import by the user in the astroI18nConfig.

2. Got it!
3. Nice, I remember one of the other i18n libraries had this same thing at the beginning. The shitty thing is that when you duplicate the user page (in other subdirectory), they would have the imports of their new file relative to the old one. Most of the people use TS alias so it's not a big deal, but if you want to collocate files with routes, this will break it (e.g one of the options you give to collocate translations).

**Comment by Alexandre-Fernandez** [comment]
> it could run the same script as you do on runtime and create a unified translation object to import by the user in the astroI18nConfig.

Good idea, I will try adding it into the future.

I updated the documentation to tell about the `pages` thing.

For the redirection I just updated the library to `2.1.13` (messed up the versioning whatever), a new method exists `astroI18n.redirect()` that you can use for redirections. @fprl
