### ISSUE TITLE
Trailing slash option causes translated page imports to be wrong

### ISSUE THREAD

**Issue by Sirius902** [Alexandre-Fernandez/astro-i18n#57]
**Describe the bug**
When the `trailingSlash` option on the `astro-i18n` config is set to `always`, import paths for the primary locale's page from secondary pages includes extra `../`.

**To Reproduce**
* Setup an Astro repo then setup `astro-i18n` by running `./node_modules/.bin/astro-i18n install`.
* Use the below `astro-i18n.config.ts`.
```ts
import { defineAstroI18nConfig } from "astro-i18n"

export default defineAstroI18nConfig({
  primaryLocale: "en",
  secondaryLocales: ["ja"],
  fallbackLocale: "en",
  trailingSlash: "always",
  run: "client+server",
  showPrimaryLocale: false,
  translationLoadingRules: [],
  translationDirectory: {},
  translations: {},
  routes: {},
})

```
* Create an index page at either `src/pages/index.astro` or `src/pages/en/index.astro` if there isn't one already.
* Run `npm run i18n:sync` and then `npm run build`.
* You will get an error like so:
```
$ astro build
12:17:43 AM [content] No content directory found. Skipping type generation.
12:17:43 AM [build] output target: static
12:17:43 AM [build] Collecting build info...
12:17:43 AM [build] Completed in 20ms.
12:17:43 AM [build] Building static entrypoints...
Could not resolve "../../index.astro" from "src/pages/ja/index.astro"
```
* Note that if you change `trailingSlash` to `never` and rerun `npm run i18n:sync` then `src/pages/ja/index.astro` will have the correct import meaning `npm run build` will complete successfully.

**Expected behavior**
I would expect the build to succeed with `trailingSlash` configured to either `never` or `always`.

**Comment by Alexandre-Fernandez** [comment]
I just fixed this in `2.0.13`. Thanks for reporting.
