### ISSUE TITLE
Cannot redirect from secondary locale page

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [Alexandre-Fernandez/astro-i18n#58]
**Describe the bug**
>     When you create the translated pages with the script you get this code in the translated route:
> 
> 
> ```ts
> ---
> import Page from "../../about.astro"
> const { props } = Astro
> ---
> <Page {...props} />
> ```
> 
> According to [the docs](https://docs.astro.build/en/reference/api-reference/#astroredirect):
> 
> > A page (and not a child component) must return the result of Astro.redirect() for the redirect to occur.
> 
> So if you set a redirect in the `primaryLocale` page, once you translate Astro gives you an error: `The response has already been sent to the browser and cannot be altered.`

#56 @fprl 

**Mandatory reproduction repository**
[Add a git repository to reproduce the bug.](https://github.com/fprl/repro-astro-i18n)

**To Reproduce**
Go to /nl/about

**Expected behavior**
Get redirected to index.

**Comment by irg1008** [comment]
Related to #86 How is this closed?
