### ISSUE TITLE
i18n:generate:pages misplaces generated pages for nested dynamic routes

### ISSUE THREAD

**Issue by gislerro** [Alexandre-Fernandez/astro-i18n#59]
**Describe the bug**
Running `npm run i18n:generate:pages` results in localized pages being created that do not follow the base locale.

Example:
A valid route in my base locale is: `/nested/static`
After generation the localized page resides at `/de/static`

**To Reproduce**
1. Create a route `src/pages/foo/index.astro` with dynamic subroutes `src/pages/foo/[slug].astro`.
2. `npm run i18n:generate:pages`

or:
1. [Clone this repo](https://github.com/gislerro/astro-i18n-v2-repro/tree/sync-debug)
2. `npm run i18n:generate:pages`

**Expected behavior**
The script generates the pages at the correct route: `de/nested/static`

**Mandatory reproduction repository**
[See here](https://github.com/gislerro/astro-i18n-v2-repro/tree/sync-debug)

**Comment by gislerro** [comment]
In my reproduction I also wasn't able to get translation to load for the dynamic subroute - I'm not entirely sure if it's due to a misconfiguration on my end though

**Comment by gislerro** [comment]
Another problem that I have which I wasn't able to reproduce is that when I run `npm run i18n:generate:pages` in my project it clutters my `src/pages`directory.
before sync:
```
└── src/
    └── pages/
        ├── de/
        │   └── ...
        ├── it/
        │   └── ...
        ├── fr/
        │   └── ...
        ├── index.astro
        ├── privacy.astro
        └── terms.astro
```
after sync:
```
└── src/
    └── pages/
        ├── privacy/
        │   └── index.astro
        ├── terms/
        │   └── index.astro
        ├── de/
        │   └── ...
        ├── it/
        │   └── ...
        ├── fr/
        │   └── ...
        ├── index.astro
        ├── privacy.astro
        └── terms.astro
```
The generated localized pages do reference the root-level files:
```javascript
// src/pages/fr/privacy/index.astro
---
import Page from "../../privacy.astro" // <----
export const prerender = true
const { props } = Astro
---
<Page {...props} />
```
So I can safely delete the `src/pages/privacy` folder.

The script also for some reason overrides all my code in `src/pages/index.astro` with the generated content which is pretty annoying to deal with.
```javascript
// src/pages/index.astro after sync
---
import Page from "../index.astro"
export const prerender = true
const { props } = Astro
---
<Page {...props} />
```

**Comment by Alexandre-Fernandez** [comment]
I just tested the command on your repo with the latest astro-i18n version and it works as expected :
![image](https://github.com/Alexandre-Fernandez/astro-i18n/assets/79476242/55014d8f-e658-4ad5-a498-19ce8de16f03)
Try with the latest version + what OS are you on ?

**Comment by gislerro** [comment]
I've created a branch for the reproduction so you should switch to the `sync-debug` branch after cloning the repo. I forgot that cloning a repo only clones the default branch, sorry for that. 
On that branch im using `"astro-i18n": "^2.1.13"`

I'm on WSL with Ubuntu 22.04.2 LTS.
```
// npm run astro info
Astro                    v3.2.4
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

**Comment by Alexandre-Fernandez** [comment]
Thanks for reporting this, it should be fixed now, try with v`2.1.14`. @gislerro

**Comment by gislerro** [comment]
Looks like it's working 👍

**Comment by Alexandre-Fernandez** [comment]
> PS: The reason for the cluttering and overriding of my index.astro file was that I had my primaryLocale in the secondaryLocales in my real project

I just added an error for that in v`2.1.15`.
