### ISSUE TITLE
Cyrillic URLs seem to cause issues

### ISSUE THREAD

**Issue by jvzr** [Alexandre-Fernandez/astro-i18n#60]
**Describe the bug**
When using cyrillic in URLs, and switching from locale to locale (with the provided LocaleSwitcher component, everything works as expected except when going from a URL containing cyrillic to a locale which URL is not cyrillic.

**To Reproduce**
With this config:
```
routes: {
    "de": {
      "cookies": "cookie-richtlinien",
      "contact": "kontakt",
    },
    "ru": {
      "cookies": "cookies",
      "contact": "контакты",
    },
  },
```
Starting on `de/kontakt`, the link to the russian version is `ru/контакты`.
Going to `ru/cookies` with the navigation works as well. On that page, the German page is `de/cookie-richlinien` as expected.
Going back to `ru/контакты`, the German versions of the page show up as `de/контакты` leading to a 404.
This works with any other language as destination: they are all listed with the cyrillic URL.

_I was able to fix this by decoding the URI in LocaleSwitcher:_

```
let links = astroI18n.locales.map((locale) => ({
    locale,
    href: l(decodeURI(Astro.url.pathname), params, {
        targetLocale: locale,
    }),
    label: labels[locale] || locale,
}));
```

**Mandatory reproduction repository**
[Reproduction of the bug](https://github.com/jvzr/astro-i18n-ru-bug)

**Comment by Alexandre-Fernandez** [comment]
It should be fixed try again with the last version.

**Comment by jvzr** [comment]
Yes indeed! Thank you!
