### ISSUE TITLE
SyntaxError: Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by Nkay** [Alexandre-Fernandez/astro-i18n#66]
**Describe the bug**
Astro won't run

**To Reproduce**
1. clone https://github.com/Nkay/i18n-bug-reproduce
2. type npm i && npm run start

Without astro-i18n, it works.

**Expected behavior**
Astro should run

**Mandatory reproduction repository**
https://github.com/Nkay/i18n-bug-reproduce

**Comment by Alexandre-Fernandez** [comment]
This is happening because you are using the default export in your `astro.config`.
`astro-i18n` doesn't use the integrations API anymore, it is now a middleware.
```ts
// old
import i18n from "astro-i18n"
import { defineConfig } from 'astro/config';
export default defineConfig({
  integrations: [i18n()]
});
```
```ts
// new
import { defineConfig } from 'astro/config';
export default defineConfig({});
```
@Nkay @IsaacMarovitz
