### ISSUE TITLE
Can't build on Vercel edge worker

### ISSUE THREAD

**Issue by beeb** [Alexandre-Fernandez/astro-i18n#7]
When trying to build a test project using `astro-i18n` on Vercel edge workers, I get the following error:

```
[commonjs--resolver] Cannot bundle Node.js built-in "url" imported from "node_modules/.pnpm/astro-i18n@1.3.2/node_modules/astro-i18n/dist/src/index.mjs". Consider disabling ssr.noExternal or remove the built-in dependency.
```

I couldn't find any documentation about using this library without Node.js available. Is that not supported? Would there be a way to not depend on Node.js APIs and make this compatible with, for instance, `@astrojs/vercel/edge` ?

**Comment by beeb** [comment]
I understand that Node.js is needed to get the content of the translation files when a path is provided for them. But in my case I'm not using that and instead do:

```ts
// astro.i18n.config.ts
import { defineAstroI18nConfig } from 'astro-i18n'
import en from './src/locales/en.json'

export default defineAstroI18nConfig({
	defaultLangCode: 'en',
	supportedLangCodes: [],
	showDefaultLangCode: false,
	translations: {
		en,
	},
	routeTranslations: {}
})
```

**Comment by Alexandre-Fernandez** [comment]
Hi, thanks for reporting this problem. 
Unfortunately, I do not use edge functions myself and I'm not willing to make a PR for this.
You can make a PR for this or try using [astro-i18next](https://github.com/yassinedoghri/astro-i18next).

**Comment by beeb** [comment]
Thanks for the reply. The other library has the same issue. Maybe I'll wait some more until they can fix it.

Edge functions are great, they have lower latency and startup times, you should look into it!

**Comment by jlarmstrongiv** [comment]
For more information on what can be used in the edge runtime, see https://edge-runtime.vercel.app/

**Comment by Alexandre-Fernandez** [comment]
Closing this, it should work with the new version if not tell me I'll reopen the issue. I have no way of testing this myself.
