### ISSUE TITLE
Version 2.2.2 middleware break Picture tags

### ISSUE THREAD

**Issue by Herob527** [Alexandre-Fernandez/astro-i18n#76]
**Describe the bug**
When I was developing app, I noticed images weren't loading properly (only alt image)

After messing around I disabled middleware for i18n and images came to life

Rollbacking to 2.2.1 proved it was astro-i18n update since on 2.2.1 it works

**To Reproduce**
1. Install latest astro-i18n
2. Add some Picture and Image tags
3. Check the result of _image query (it'll tell image is invalid and alt text will show up)

**Expected behavior**
Image loading properly

**Mandatory reproduction repository**
https://github.com/Herob527/astro-i18n-image-reproduction-repo

**Additional images**
Result without middleware:
![without-middleware](https://github.com/Alexandre-Fernandez/astro-i18n/assets/61355107/353d5b57-dc77-4133-beb4-adb3bee4c0ce)

Result with middleware: 
![with-middleware](https://github.com/Alexandre-Fernandez/astro-i18n/assets/61355107/fc0e6940-aaab-4ab2-b3d1-adef24aab6f2)
![image](https://github.com/Alexandre-Fernandez/astro-i18n/assets/61355107/b31e45f9-367d-4604-96c9-1ea21fc993fb)

**Comment by Alexandre-Fernandez** [comment]
@Herob527 can you try with `defineAstroI18nConfig({ run: "server" })` ?

**Comment by Alexandre-Fernandez** [comment]
Can you try with [this version](https://github.com/Alexandre-Fernandez/astro-i18n/blob/debug/astro-i18n-2.2.2.tgz) ? It's the 2.2.2 with a bunch of `console.logs`. To install a local package you can `pnpm add ./astro-i18n-2.2.2.tgz`.

**Comment by Herob527** [comment]
I did thing that I used Ctrl+F5 to ensure image will not be taken for browser cache

Logs with client+server

> astro-i18n-image-issue-reproduction@0.0.1 start
> astro dev


 astro  v4.2.1 ready in 101 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

23:33:11 watching for file changes...
response Response {
  [Symbol(realm)]: { settingsObject: {} },
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: false,
    requestIncludesCredentials: false,
    type: 'default',
    status: 200,
    timingInfo: null,
    cacheState: '',
    statusText: 'OK',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [],
    body: { stream: undefined, source: null, length: null }
  },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(1) { 'content-type' => [Object] },
    [Symbol(headers map sorted)]: null
  },
  [Symbol(astro.cookies)]: AstroCookies {}
}
redirection null
response.bodyUsed false
body <!DOCTYPE html><html lang="en"> <head><meta charset="utf-8"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta name="viewport" content="width=device-width"><meta name="generator" content="Astro v4.2.1"><title>Astro</title><script type="module" src="/@vite/client"></script>
<script type="module" src="/@fs/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/dist/runtime/client/dev-toolbar/entrypoint.js?v=64ded069"></script>
<script>window.__astro_dev_toolbar__ = {"root":"/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/","version":"4.2.1","debugInfo":"Astro                    v4.2.1\nNode                     v20.11.0\nSystem                   Linux (x64)\nPackage Manager          npm\nOutput                   static\nAdapter                  none\nIntegrations             none"}</script></head> <body data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/src/pages/index.astro" data-astro-source-loc="15:8"> <h1 data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/src/pages/index.astro" data-astro-source-loc="16:7">Astro</h1> <picture data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="66:33"> <source srcset="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fsome_icon.svg%3ForigWidth%3D128%26origHeight%3D128%26origFormat%3Dsvg&#38;f=svg" type="image/svg" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="74:6"> <img src="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fsome_icon.svg%3ForigWidth%3D128%26origHeight%3D128%26origFormat%3Dsvg&#38;f=svg" alt="favicon" width="128" height="128" loading="lazy" decoding="async" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="82:3"> </picture> <picture data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="66:33"> <source srcset="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fcat.jpg%3ForigWidth%3D682%26origHeight%3D909%26origFormat%3Djpg&#38;f=webp" type="image/webp" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="74:6"> <img src="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fcat.jpg%3ForigWidth%3D682%26origHeight%3D909%26origFormat%3Djpg&#38;f=jpg" alt="cat" width="682" height="909" loading="lazy" decoding="async" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="82:3"> </picture> </body></html>
new body <!DOCTYPE html><html lang="en"> <head><meta charset="utf-8"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta name="viewport" content="width=device-width"><meta name="generator" content="Astro v4.2.1"><title>Astro</title><script type="module" src="/@vite/client"></script>
<script type="module" src="/@fs/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/dist/runtime/client/dev-toolbar/entrypoint.js?v=64ded069"></script>
<script>window.__astro_dev_toolbar__ = {"root":"/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/","version":"4.2.1","debugInfo":"Astro                    v4.2.1\nNode                     v20.11.0\nSystem                   Linux (x64)\nPackage Manager          npm\nOutput                   static\nAdapter                  none\nIntegrations             none"}</script><script id="__astro-i18n__" type="application/json">{"locale":"en","route":"/","config":{"primaryLocale":"en","secondaryLocales":[],"showPrimaryLocale":false,"trailingSlash":"never"},"translations":{"/":{},"common":{"en":{"your_common":{"default":"translations here","variants":[]},"they.can":{"default":"be nested","variants":[]}}}},"segments":{},"formatters":{}}</script></head> <body data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/src/pages/index.astro" data-astro-source-loc="15:8"> <h1 data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/src/pages/index.astro" data-astro-source-loc="16:7">Astro</h1> <picture data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="66:33"> <source srcset="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fsome_icon.svg%3ForigWidth%3D128%26origHeight%3D128%26origFormat%3Dsvg&#38;f=svg" type="image/svg" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="74:6"> <img src="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fsome_icon.svg%3ForigWidth%3D128%26origHeight%3D128%26origFormat%3Dsvg&#38;f=svg" alt="favicon" width="128" height="128" loading="lazy" decoding="async" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="82:3"> </picture> <picture data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="66:33"> <source srcset="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fcat.jpg%3ForigWidth%3D682%26origHeight%3D909%26origFormat%3Djpg&#38;f=webp" type="image/webp" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="74:6"> <img src="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fcat.jpg%3ForigWidth%3D682%26origHeight%3D909%26origFormat%3Djpg&#38;f=jpg" alt="cat" width="682" height="909" loading="lazy" decoding="async" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="82:3"> </picture> </body></html>
23:33:12 [200] / 139ms
response Response {
  [Symbol(realm)]: { settingsObject: {} },
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: false,
    requestIncludesCredentials: false,
    type: 'default',
    status: 200,
    timingInfo: null,
    cacheState: '',
    statusText: 'OK',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [],
    body: { stream: undefined, source: null, length: null }
  },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(1) { 'content-type' => [Object] },
    [Symbol(headers map sorted)]: null
  },
  [Symbol(astro.cookies)]: AstroCookies {}
}
redirection null
response.bodyUsed false
body <!DOCTYPE html><html lang="en"> <head><meta charset="utf-8"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta name="viewport" content="width=device-width"><meta name="generator" content="Astro v4.2.1"><title>Astro</title><script type="module" src="/@vite/client"></script>
<script type="module" src="/@fs/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/dist/runtime/client/dev-toolbar/entrypoint.js?v=64ded069"></script>
<script>window.__astro_dev_toolbar__ = {"root":"/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/","version":"4.2.1","debugInfo":"Astro                    v4.2.1\nNode                     v20.11.0\nSystem                   Linux (x64)\nPackage Manager          npm\nOutput                   static\nAdapter                  none\nIntegrations             none"}</script></head> <body data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/src/pages/index.astro" data-astro-source-loc="15:8"> <h1 data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/src/pages/index.astro" data-astro-source-loc="16:7">Astro</h1> <picture data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="66:33"> <source srcset="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fsome_icon.svg%3ForigWidth%3D128%26origHeight%3D128%26origFormat%3Dsvg&#38;f=svg" type="image/svg" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="74:6"> <img src="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fsome_icon.svg%3ForigWidth%3D128%26origHeight%3D128%26origFormat%3Dsvg&#38;f=svg" alt="favicon" width="128" height="128" loading="lazy" decoding="async" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="82:3"> </picture> <picture data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="66:33"> <source srcset="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fcat.jpg%3ForigWidth%3D682%26origHeight%3D909%26origFormat%3Djpg&#38;f=webp" type="image/webp" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="74:6"> <img src="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fcat.jpg%3ForigWidth%3D682%26origHeight%3D909%26origFormat%3Djpg&#38;f=jpg" alt="cat" width="682" height="909" loading="lazy" decoding="async" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="82:3"> </picture> </body></html>
new body <!DOCTYPE html><html lang="en"> <head><meta charset="utf-8"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta name="viewport" content="width=device-width"><meta name="generator" content="Astro v4.2.1"><title>Astro</title><script type="module" src="/@vite/client"></script>
<script type="module" src="/@fs/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/dist/runtime/client/dev-toolbar/entrypoint.js?v=64ded069"></script>
<script>window.__astro_dev_toolbar__ = {"root":"/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/","version":"4.2.1","debugInfo":"Astro                    v4.2.1\nNode                     v20.11.0\nSystem                   Linux (x64)\nPackage Manager          npm\nOutput                   static\nAdapter                  none\nIntegrations             none"}</script><script id="__astro-i18n__" type="application/json">{"locale":"en","route":"/","config":{"primaryLocale":"en","secondaryLocales":[],"showPrimaryLocale":false,"trailingSlash":"never"},"translations":{"/":{},"common":{"en":{"your_common":{"default":"translations here","variants":[]},"they.can":{"default":"be nested","variants":[]}}}},"segments":{},"formatters":{}}</script></head> <body data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/src/pages/index.astro" data-astro-source-loc="15:8"> <h1 data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/src/pages/index.astro" data-astro-source-loc="16:7">Astro</h1> <picture data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="66:33"> <source srcset="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fsome_icon.svg%3ForigWidth%3D128%26origHeight%3D128%26origFormat%3Dsvg&#38;f=svg" type="image/svg" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="74:6"> <img src="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fsome_icon.svg%3ForigWidth%3D128%26origHeight%3D128%26origFormat%3Dsvg&#38;f=svg" alt="favicon" width="128" height="128" loading="lazy" decoding="async" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="82:3"> </picture> <picture data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="66:33"> <source srcset="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fcat.jpg%3ForigWidth%3D682%26origHeight%3D909%26origFormat%3Djpg&#38;f=webp" type="image/webp" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="74:6"> <img src="/_image?href=%2F%40fs%2Fhome%2Fszymon%2FDesktop%2FProjects%2Fastro-i18n-image-issue-reproduction%2Fsrc%2Fassets%2Fcat.jpg%3ForigWidth%3D682%26origHeight%3D909%26origFormat%3Djpg&#38;f=jpg" alt="cat" width="682" height="909" loading="lazy" decoding="async" data-astro-source-file="/home/szymon/Desktop/Projects/astro-i18n-image-issue-reproduction/node_modules/.pnpm/astro@4.2.1_typescript@5.3.3/node_modules/astro/components/Picture.astro" data-astro-source-loc="82:3"> </picture> </body></html>
23:33:16 [200] / 17ms
response Response {
  [Symbol(realm)]: { settingsObject: {} },
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: false,
    requestIncludesCredentials: false,
    type: 'default',
    status: 200,
    timingInfo: null,
    cacheState: '',
    statusText: '',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [],
    body: { stream: undefined, source: [Uint8Array], length: 749 }
  },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(4) {
      'content-type' => [Object],
      'cache-control' => [Object],
      'etag' => [Object],
      'date' => [Object]
    },
    [Symbol(headers map sorted)]: null
  }
}
redirection null
response.bodyUsed false
body <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 128 128">
    <path d="M50.4 78.5a75.1 75.1 0 0 0-28.5 6.9l24.2-65.7c.7-2 1.9-3.2 3.4-3.2h29c1.5 0 2.7 1.2 3.4 3.2l24.2 65.7s-11.6-7-28.5-7L67 45.5c-.4-1.7-1.6-2.8-2.9-2.8-1.3 0-2.5 1.1-2.9 2.7L50.4 78.5Zm-1.1 28.2Zm-4.2-20.2c-2 6.6-.6 15.8 4.2 20.2a17.5 17.5 0 0 1 .2-.7 5.5 5.5 0 0 1 5.7-4.5c2.8.1 4.3 1.5 4.7 4.7.2 1.1.2 2.3.2 3.5v.4c0 2.7.7 5.2 2.2 7.4a13 13 0 0 0 5.7 4.9v-.3l-.2-.3c-1.8-5.6-.5-9.5 4.4-12.8l1.5-1a73 73 0 0 0 3.2-2.2 16 16 0 0 0 6.8-11.4c.3-2 .1-4-.6-6l-.8.6-1.6 1a37 37 0 0 1-22.4 2.7c-5-.7-9.7-2-13.2-6.2Z" />
    <style>
        path { fill: #000; }
        @media (prefers-color-scheme: dark) {
            path { fill: #FFF; }
        }
    </style>
</svg>

no html
23:33:16 [200] /_image 35ms
response Response {
  [Symbol(realm)]: { settingsObject: {} },
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: false,
    requestIncludesCredentials: false,
    type: 'default',
    status: 200,
    timingInfo: null,
    cacheState: '',
    statusText: '',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [],
    body: { stream: undefined, source: [Uint8Array], length: 58684 }
  },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(4) {
      'content-type' => [Object],
      'cache-control' => [Object],
      'etag' => [Object],
      'date' => [Object]
    },
    [Symbol(headers map sorted)]: null
  }
}
redirection null
response.bodyUsed false
body RIFF4�

Logs with server:

> astro-i18n-image-issue-reproduction@0.0.1 start
> astro dev


 astro  v4.2.1 ready in 108 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

23:33:30 watching for file changes...
23:33:31 [200] / 127ms
23:33:33 [200] / 15ms
23:33:33 [200] /_image 55ms
23:33:33 [200] /_image 161ms

**Comment by Alexandre-Fernandez** [comment]
Can you please retry with 2.2.4 ? I pushed a possible fix based on the logs. If it doesn't work please also try with the SVG alone and the Raster image alone.

**Comment by Herob527** [comment]
2.2.3 and 2.2.4 for my usage worked fine

**Comment by Alexandre-Fernandez** [comment]
great
